name: Build and Push Guestbook to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Solution simple et efficace
    timeout-minutes: 20
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/guestbook:latest
          ${{ secrets.DOCKER_USERNAME }}/guestbook:${{ github.sha }}
          
    - name: Update Helm chart
      run: |
        # Mettre à jour le tag dans values.yaml
        sed -i "s/tag: .*/tag: \"${{ github.sha }}\"/" helm/guestbook/values.yaml
        
        # Committer le changement
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add helm/guestbook/values.yaml
        git commit -m "Update image tag to ${{ github.sha }}" || exit 0
        git push