name: Simple Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, kubernetes]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build and Push
      run: |
        # Build avec tag SHA et latest
        docker build -t ${{ secrets.DOCKER_USERNAME }}/guestbook:${{ github.sha }} .
        docker build -t ${{ secrets.DOCKER_USERNAME }}/guestbook:latest .
        
        # Push vers Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/guestbook:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/guestbook:latest
        
        echo "✅ Images pushed successfully!"
        
    - name: Cleanup
      run: |
        docker rmi ${{ secrets.DOCKER_USERNAME }}/guestbook:${{ github.sha }} || true
        docker rmi ${{ secrets.DOCKER_USERNAME }}/guestbook:latest || true
