name: Build and Push Guestbook to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, kubernetes]
    timeout-minutes: 20
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build and push with Kaniko
      uses: aevea/action-kaniko@master
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/guestbook
        tag: latest,${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
        build_args: |
          BUILDPLATFORM=linux/arm64
